# Generated by Django 3.2.5 on 2021-07-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('survey_question_bindings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('binding_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey_question_bindings.surveyquestionbinding')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
