# Generated by Django 3.2.5 on 2021-07-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_responses',
            },
        ),
    ]
