# Generated by Django 3.2.5 on 2021-08-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='answer',
            field=models.JSONField(),
        ),
    ]
