# Generated by Django 3.2.5 on 2021-07-13 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_question_bindings', '0001_initial'),
        ('users', '0001_initial'),
        ('survey_responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='binding_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey_question_bindings.surveyquestionbinding'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
