# Generated by Django 3.2.5 on 2021-07-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_responses', '0002_auto_20210713_1225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyresponse',
            table='survey_responses',
        ),
    ]
