# Generated by Django 3.2.5 on 2021-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_responses', '0002_alter_surveyresponse_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
