# Generated by Django 3.2.5 on 2021-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('user_type', models.CharField(choices=[('temp', 'Temp'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=10)),
            ],
        ),
    ]
