# Generated by Django 3.2.5 on 2021-07-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_question_bindings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='surveyquestionbinding',
            table='survey_question_bindings',
        ),
    ]
