# Generated by Django 3.2.5 on 2021-07-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('editing', 'Editing'), ('published', 'Published'), ('closed', 'Closed'), ('deleted', 'Deleted')], max_length=20)),
                ('meta', models.JSONField(null=True)),
                ('view_type', models.CharField(choices=[('scroll', 'Scroll'), ('slide', 'Slide')], max_length=20)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
