# Generated by Django 3.2.5 on 2021-07-16 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='link',
            new_name='result_link',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
