# Generated by Django 3.2.5 on 2021-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210716_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
