# Generated by Django 3.2.5 on 2021-07-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='surveys',
        ),
    ]
