# Generated by Django 3.2.5 on 2021-08-09 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210723_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='view',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
