# Generated by Django 3.2.5 on 2021-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210809_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user_email',
            field=models.EmailField(max_length=320, null=True),
        ),
    ]
