# Generated by Django 3.2.5 on 2021-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='contents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
    ]
